export const PEA_COUNTRIES = [
  "FR","DE","IT","ES","PT","NL","BE","AT","FI","IE","GR","LU","MT","CY",
  "SK","SI","EE","LV","LT","SE","DK","NO","IS","PL","CZ","HU","RO","BG","HR","LI","GB"
];

export const COUNTRY_DATA = [
  { code: "KR", name: "Corée du Sud", flag: "🇰🇷", region: "Asie" },
  { code: "IN", name: "Inde", flag: "🇮🇳", region: "Asie" },
  { code: "ID", name: "Indonésie", flag: "🇮🇩", region: "Asie" },
  { code: "MY", name: "Malaisie", flag: "🇲🇾", region: "Asie" },
  { code: "PH", name: "Philippines", flag: "🇵🇭", region: "Asie" },
  { code: "TH", name: "Thaïlande", flag: "🇹🇭", region: "Asie" },
  { code: "VN", name: "Vietnam", flag: "🇻🇳", region: "Asie" },
  { code: "CN", name: "Chine", flag: "🇨🇳", region: "Asie" },
  { code: "JP", name: "Japon", flag: "🇯🇵", region: "Asie" },
  { code: "TW", name: "Taïwan", flag: "🇹🇼", region: "Asie" },
  { code: "SG", name: "Singapour", flag: "🇸🇬", region: "Asie" },
  { code: "HK", name: "Hong Kong", flag: "🇭🇰", region: "Asie" },
  { code: "US", name: "États-Unis", flag: "🇺🇸", region: "Amérique" },
  { code: "BR", name: "Brésil", flag: "🇧🇷", region: "Amérique" },
  { code: "MX", name: "Mexique", flag: "🇲🇽", region: "Amérique" },
  { code: "AR", name: "Argentine", flag: "🇦🇷", region: "Amérique" },
  { code: "CL", name: "Chili", flag: "🇨🇱", region: "Amérique" },
  { code: "CO", name: "Colombie", flag: "🇨🇴", region: "Amérique" },
  { code: "PE", name: "Pérou", flag: "🇵🇪", region: "Amérique" },
  { code: "GB", name: "Royaume-Uni", flag: "🇬🇧", region: "Europe" },
  { code: "DE", name: "Allemagne", flag: "🇩🇪", region: "Europe" },
  { code: "FR", name: "France", flag: "🇫🇷", region: "Europe" },
  { code: "SE", name: "Suède", flag: "🇸🇪", region: "Europe" },
  { code: "NO", name: "Norvège", flag: "🇳🇴", region: "Europe" },
  { code: "DK", name: "Danemark", flag: "🇩🇰", region: "Europe" },
  { code: "FI", name: "Finlande", flag: "🇫🇮", region: "Europe" },
  { code: "NL", name: "Pays-Bas", flag: "🇳🇱", region: "Europe" },
  { code: "BE", name: "Belgique", flag: "🇧🇪", region: "Europe" },
  { code: "IT", name: "Italie", flag: "🇮🇹", region: "Europe" },
  { code: "ES", name: "Espagne", flag: "🇪🇸", region: "Europe" },
  { code: "PT", name: "Portugal", flag: "🇵🇹", region: "Europe" },
  { code: "GR", name: "Grèce", flag: "🇬🇷", region: "Europe" },
  { code: "PL", name: "Pologne", flag: "🇵🇱", region: "Europe" },
  { code: "CZ", name: "Tchéquie", flag: "🇨🇿", region: "Europe" },
  { code: "HU", name: "Hongrie", flag: "🇭🇺", region: "Europe" },
  { code: "RO", name: "Roumanie", flag: "🇷🇴", region: "Europe" },
  { code: "BG", name: "Bulgarie", flag: "🇧🇬", region: "Europe" },
  { code: "HR", name: "Croatie", flag: "🇭🇷", region: "Europe" },
  { code: "RS", name: "Serbie", flag: "🇷🇸", region: "Europe" },
  { code: "TR", name: "Turquie", flag: "🇹🇷", region: "Europe" },
  { code: "AT", name: "Autriche", flag: "🇦🇹", region: "Europe" },
  { code: "CH", name: "Suisse", flag: "🇨🇭", region: "Europe" },
  { code: "IE", name: "Irlande", flag: "🇮🇪", region: "Europe" },
  { code: "AU", name: "Australie", flag: "🇦🇺", region: "Océanie" },
  { code: "NZ", name: "Nouvelle-Zélande", flag: "🇳🇿", region: "Océanie" },
  { code: "ZA", name: "Afrique du Sud", flag: "🇿🇦", region: "Afrique" },
  { code: "NG", name: "Nigeria", flag: "🇳🇬", region: "Afrique" },
  { code: "EG", name: "Égypte", flag: "🇪🇬", region: "Afrique" },
  { code: "MA", name: "Maroc", flag: "🇲🇦", region: "Afrique" },
  { code: "KE", name: "Kenya", flag: "🇰🇪", region: "Afrique" },
  { code: "SA", name: "Arabie Saoudite", flag: "🇸🇦", region: "Moyen-Orient" },
  { code: "AE", name: "Émirats Arabes Unis", flag: "🇦🇪", region: "Moyen-Orient" },
  { code: "QA", name: "Qatar", flag: "🇶🇦", region: "Moyen-Orient" },
  { code: "IL", name: "Israël", flag: "🇮🇱", region: "Moyen-Orient" },
  { code: "RU", name: "Russie", flag: "🇷🇺", region: "Europe" },
];

export const cycleColors = { "Expansion": "#22c55e", "Pic": "#f59e0b", "Récession": "#ef4444", "Rebond": "#3b82f6" };
export const cycleIcons = { "Expansion": "📈", "Pic": "🔝", "Récession": "📉", "Rebond": "🔄" };

export const signalColors = {
  "ACHETER FORT": { bg: "#15803d", color: "#bbf7d0" },
  "ACHETER": { bg: "#166534", color: "#86efac" },
  "CONSERVER": { bg: "#854d0e", color: "#fde68a" },
  "VENDRE": { bg: "#991b1b", color: "#fca5a5" },
  "VENDRE FORT": { bg: "#7f1d1d", color: "#fecaca" },
};
